language: csharp
solution: CoCSharp.sln

mono:
    - latest

install:
    - nuget restore CoCSharp.sln
    - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory nunitrunner

script:
    - xbuild CoCSharp.sln
    - mono ./nunitrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./CoCSharp.Test/bin/Debug/CoCSharp.Test.dll
    - cat TestResult.xml
